[package]
name = "qpaste"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["multipart"] }
rand = "0.10.2"
tokio = { version = "1.53.1", features = [
    "rt-multi-thread",
    "fs",
    "io-util",
    "signal",
] }
tokio-util = { version = "0.7.19", features = ["io"] }
tower-http = { version = "0.7.1", features = ["limit"] }
